### PR TITLE
Add `horizontal` option

### LINKED ISSUE #10: Horizontal scrolling
I was hoping to use this to implement a horizontal carousel. I was sad to see that it only supports vertical scrolling.

Would this be difficult to add?

### PR DESCRIPTION
**Pull request by jesseditson**
Fixes #10 

Did my best to keep the style consistent, also added a demo to index.html in lieu of tests - let me know if there's anything else needed!

### CODE REVIEW

**Comment by jesseditson** [comment]
**demo from index.html:**

**Comment by Stanko** [comment]
Hello @jesseditson,
Thank you! I'll merge your work, and probably release it tomorrow!

Cheers!

**Comment by oa495** [comment]
was this removed?

**Comment by Stanko** [comment]
Check method signatures:
https://github.com/Stanko/animated-scroll-to#method-signatures

**Pull request merged**
