### PR TITLE
make offset could be a callback

### PR DESCRIPTION
**Pull request by yaquawa**
Hi @Stanko , thanks for your great work !

I have a use case which the offset may vary base on the window size.
Making the offset option to be either a number or a callback function gives us more flexibility.👍🏼

### CODE REVIEW

**Comment by Stanko** [comment]
Hello @yaquawa,

Can you explain the use case a little bit more to me, because I don't get why would you need to pass a function.

I think you could just call the function directly like this:
```js
animateScrollTo(500, {
  verticalOffset: () => window.innerWidth > 600 ? 100 : 60,
});
```

Cheers!

**Comment by yaquawa** [comment]
Thanks @Stanko !

What I want to get is something like this.

```js
const offset = () => window.innerWidth > 600 ? 100 : 60;
const defaultOptions = { verticalOffset : offset };
const animateScrollTo = new AnimateScrollTo(defaultOptions);

// So I can call this instead of animateScrollTo(element, offset());
animateScrollTo.to(element);
```

But I realize the `animateScrollTo` is just a function but not a class after this PR...
Maybe it could be done as this? What do you think?
```js
const offset = () => window.innerWidth > 600 ? 100 : 60;
animateScrollTo.defaultOptions.verticalOffset = offset;

// So I can call this instead of  animateScrollTo(element, offset());
animateScrollTo(element);
```

**Comment by Stanko** [comment]
Well, `animateScrollTo` is a simple function. That means you can't do either. It doesn't return an instance, but a `Promise`.

If your options are different than default options, there is no way to overwrite them globally.

When you need dynamic options (in your case depending on the screen size) just create a function that returns options. Something like this:

```js
function getOptions() {
  let verticalOffset = 100;

  if (window.innerWidth < 1000) {
    verticalOffset = 80;
  } else if   if (window.innerWidth < 600) {
    verticalOffset = 60;
  } 

  return {
    verticalOffset,
    // ... other options
  };
}

// Then you call animateScrollTo anywhere in the code with:
animateScrollTo(element, getOptions());
```

**Comment by yaquawa** [comment]
Thanks @Stanko , I'll do it as you described 👍🏼

**Pull request closed without merging**
